# Site settings
title: 坤坤同学
description: '不积跬步无以至千里'
url: 'https://wanyakun.github.io'
baseurl: '/' 
google_analytics: 'UA-73111312-1'
disqus_shortname: 'wanyakun'

author:
  name: 'wanyakun'
  email: yakun.wan@gmail.com
  twitter_username: wanyakun
  facebook_username: wanyakun
  github_username:  wanyakun
  linkedin_username:  wanyakun

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
