---
title: 坤坤同学 ❤ 摄影
timezone: UTC+8
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source: src
destination: dist
permalink: "/:categories/:title"

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - dev
  - .tern-project
  - .DS_Store
  - design

keep_files:
  - .git
  - .gitignore
  - CNAME

  # Build settings
markdown: kramdown
plugins:
  - jekyll-pug
