---
title: 坤坤同学 ❤ 摄影
timezone: UTC+8
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source: src
destination: dist
permalink: "/:categories/:title"
